#!/usr/bin/perl

use Data::Dumper;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Genbank qw(parse_regionfile parse_featurefile set_sequence sequence_for_interval sequin_feature);
use Subfunctions qw(parse_fasta merge_to_featuretable);

# a regionfile is the output of parse_blast.pl comparing the fastafile to the reference fasta file from genbank.pl
my $regionfile = shift;

# fastafile is the new fasta file to be aligned: same as fasta file used in parse_blast.pl
my $fastafile = shift;

# featurefile is the feature table file generated by genbank.pl
my $featurefile = shift;
my $outfile = shift;

merge_to_featuretable ($regionfile, $fastafile, $featurefile, $outfile);

# >Features Populus trichocarpa chloroplast, complete genome.
# 1	157033	source
# 			mol_type	genomic DNA
# 			organism	Populus trichocarpa
# 77	4	gene
# 			gene	trnH
# 77	4	tRNA
# 			gene	trnH
# 			product	tRNA-His

